// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCer3UTLLDHhqAQdeq-6qe1v3fLT-pgqqs',
    appId: '1:634982141626:web:d9ec7b92d11c1dc5fbbc83',
    messagingSenderId: '634982141626',
    projectId: 'eccomercefirebase',
    authDomain: 'eccomercefirebase.firebaseapp.com',
    storageBucket: 'eccomercefirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWHhtwOJAPsH9kgN1Bav0jXCkGp6d2cc',
    appId: '1:634982141626:android:88e5a942655781dcfbbc83',
    messagingSenderId: '634982141626',
    projectId: 'eccomercefirebase',
    storageBucket: 'eccomercefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkdW82VOp5P1rQUSlffbkgANSOkI_wtks',
    appId: '1:634982141626:ios:d9c6ff90d1dc1d90fbbc83',
    messagingSenderId: '634982141626',
    projectId: 'eccomercefirebase',
    storageBucket: 'eccomercefirebase.appspot.com',
    iosClientId: '634982141626-638domrhit5pe49agsh8a069blmm8l8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFirebase',
  );
}
